# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012fcb30603e52b4dc0206e31715b2cf91555d1ae2b51d521468eaa1cf2530e7af353ab0e6d94223df299ea2cc52d7d8cfa419300dd29247bd881b8d7922c63d

test:
  secret_key_base: 09c7c5c5c9c44131c7ef0d5807b47b9dab93c6e7fbb31697ec5e146072b6de9cd2468a2796a4fc18a3f7212d95d8ee8283f10ab05f689f32037b6e30cf0c5e47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
